### ISSUE TITLE
Test Run 'status' update

### ISSUE THREAD

**Issue by diannelli** [allankilpatrick/pytest-testrail#15]
Hi @allankilpatrick,

I installed your insteresting plugin on [Tierra_qa package](https://github.com/tierratelematics/tierra_qa) but I would like to understand if the status of each test runs created by the plugin can be set.
Currently 'Untested' string appears on each automated test runs:

![image](https://cloud.githubusercontent.com/assets/16033815/19068753/303947ae-8a24-11e6-85bb-4326ab50fe8c.png)

Let me know if the plugin is able to do it (through the proper API).

Regards.
Damiano

**Comment by allankilpatrick** [comment]
Hi,

Looking at the API this isn't possible to manually set a test run status. The status will be updated depending on the test cases added to the run I believe.

http://docs.gurock.com/testrail-api2/reference-runs

**Comment by diannelli** [comment]
Which API's are currently used by your package to set each tests status?
I noticed that only 'add_results_for_case' is used to update results.

It seems that ['add_results_for case'](http://docs.gurock.com/testrail-api2/reference-results#add_result_for_case) or the (next) 'add_result' funtion should perform an update of the test runs status in TestRail.

Do you think it can be added to the package?

**Comment by diannelli** [comment]
Hi @allankilpatrick, 
do you have any feedback about the previous question?

**Comment by allankilpatrick** [comment]
Hi,

The testrun status should be updated when any test inside the run changes. Are you saying this isn't happening ?

**Comment by allankilpatrick** [comment]
Closing now response for 2 months, please reopen if required.
