### ISSUE TITLE
Custom test run name

### ISSUE THREAD

**Issue by skipkent** [allankilpatrick/pytest-testrail#16]
Hello and thanks for this great plugin!  I was wondering if there is a way to override the plugin.testrun_name() method so that results can be posted under a run with a specific name.

Thanks,

-Kent

**Comment by allankilpatrick** [comment]
Hi @skipkent 

It could be override via a command flag
py.test --testrail --tr_name 'run name'

I'll see what come up with, also feel free to create a PR.

**Comment by skipkent** [comment]
Sounds great, thanks Allan!

**Comment by allankilpatrick** [comment]
@skipkent 
https://github.com/allankilpatrick/pytest-testrail/pull/17

Give that a go, see if that is what you are after.

**Comment by skipkent** [comment]
That looks perfect!  I downloaded the source code, checked out the 
custom-run-name branch and then did a
$ make requirements

I'm not used to running branch builds so I may have goofed something 
here, but when I use the flag I get a 'unrecognized arguments' error.

It looks like I've got the branch installed:

$ pip list |grep -i rail
pytest-testrail (0.0.9, 
/Users/kwood/Library/Python/2.7/lib/python/site-packages)

And here's my usage of the flag on the command line:
$ py.test eureqa_test.py --env='localhost_secure' 
--testrail=../configuration/testrail.cfg --tr_name='test'

Thanks,

-Kent

**Comment by allankilpatrick** [comment]
You need to install the plugin from the branch, looks like you done `pip install pytest-testrail` and version 0.0.9 is installed. 
So to install it from a local version:
`pip install -e /path/to/clonedrepo`

That will install the checked out version 0.0.10

**Comment by skipkent** [comment]
Got it working now and it's perfect.  Thanks for the great work!

Cheers,

-Kent

**Comment by allankilpatrick** [comment]
Its now deployed to pypi `pip install pytest-testrail` will give you the latest version
Closing resolved in version 0.0.10

**Comment by Azee77** [comment]
is this available in the recent build? 
pytest testcases\test_ui_login.py --os ubuntu16 --testrail --tr_name azee_run
pytest: error: unrecognized arguments: --tr_name azee_run
