### ISSUE TITLE
License for project?

### ISSUE THREAD

**Issue by chartjes** [allankilpatrick/pytest-testrail#4]
Hi @allankilpatrick 

I work at Mozilla as part of Firefox Test Engineering and we would like to use this plugin and refactor it to be more Python 3 friendly and add some more features that would be useful to us. We can't use it right now because you have not provided a license for your code. Would you accept a PR that adds a license compatible with pytest?

**Comment by allankilpatrick** [comment]
Hi @chartjes 
PRs are always welcome, please feel free to submit one and i'll take a look once I get time.

**Comment by allankilpatrick** [comment]
Resolved : https://github.com/allankilpatrick/pytest-testrail/pull/5
